steps:
  # install / setup ci
  - name: $PROJECT_NODE_VERSION
    entrypoint: npm
    args: ['install']

  #
  # Generate the statis site
  #
  - name: $PROJECT_NODE_VERSION
    entrypoint: npm
    args: ['--openssl-legacy-provider', 'run', 'generate']

  #
  # Deploy to firebase channel, using the PR #
  # store log to /workspace to get the channel URL
  #
  - name: gcr.io/$PROJECT_ID/firebase
    entrypoint: bash
    args: ['-c', 'firebase deploy --project=$PROJECT_ID--config=firebase.json --only hosting:$PROJECT_HOST_NAME']

options:
  logging: CLOUD_LOGGING_ONLY