name: BCREGISTRY UI CD

on:
  push:
    branches:
      - firebase
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"
      tagname:
        description: "Tag name"
        required: false
        default: ""

defaults:
  run:
    shell: bash

env:
  APP_NAME: "bcregistry"
  TAG_NAME: "dev"

jobs:
  bcregistry-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'pwei1018/bcregistry'
    environment:
      name: "test"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: Set env by input
        run: |
          echo "TAG_NAME=test" >> $GITHUB_ENV

      - name: tagcheckout
        uses: actions/checkout@v3

      - name: get latest tag
        id: gettag
        run: |
          echo "${{ env.TAG_NAME }}"
          LATEST_TAG='dev'
          if [[ "${{ env.TAG_NAME }}" == "test" ]]; then
            echo "123"
            echo $(git tag --sort=committerdate | grep dev | tail -1)
            LATEST_TAG=$(git tag --sort=committerdate | grep dev | tail -1)
          elif [[ "${{ env.TAG_NAME }}" == "prod" ]]; then
            echo "456"
            git tag --sort=committerdate | grep dev | tail -1
            LATEST_TAG=$(git tag --sort=committerdate | grep test | tail -1)
          else
            echo "789"
          fi

          echo "$LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: confirm tag
        run: |
          echo ${{ steps.gettag.outputs.LATEST_TAG }}

      - name: tagcheckout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.gettag.outputs.LATEST_TAG }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.TAG_NAME }}.

  bcregistry-cd-by-dispatch:
    runs-on: ubuntu-20.04

    if: github.event_name == 'workflow_dispatch' && github.repository == 'pwei1018/bcregistry'
    environment:
      name: "${{ github.event.inputs.environment }}"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: Set env by input
        run: |
          echo "TAG_NAME=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: get latest tag
        id: gettag
        run: |
          echo "LATEST_TAG=$(git tag --sort=committerdate | grep ${{ env.TAG_NAME }} | tail -1)">> $GITHUB_OUTPUT

      - name: confirm tag
        run: |
          echo ${{ steps.gettag.outputs.LATEST_TAG }}

      - name: tagcheckout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.gettag.outputs.LATEST_TAG }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.TAG_NAME }}.