name: BCREGISTRY UI CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"
      tagname:
        description: "Tag name"
        required: false
        default: ""

defaults:
  run:
    shell: bash

env:
  APP_NAME: "bcregistry"
  TAG_NAME: "dev"

jobs:
  bcregistry-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'pwei1018/bcregistry'
    environment:
      name: "dev"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      # Get environment variables from 1password
      - name: Setup .env file
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_URL }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          APP_ENV: ${{ env.TAG_NAME }}
        run: |
          curl -sSfo op.zip \
              https://cache.agilebits.com/dist/1P/op2/pkg/v2.0.0/op_linux_amd64_v2.0.0.zip \
              && unzip -od /usr/local/bin/ op.zip \
              && rm op.zip ;\
          SENTRY_1=$(op read -n op://sentry/${{ env.TAG_NAME }}/ppr-api/SENTRY_DSN)
          echo "$SENTRY_1"          

  bcregistry-cd-by-dispatch:
    runs-on: ubuntu-20.04

    if: github.event_name == 'workflow_dispatch' && github.repository == 'pwei1018/bcregistry'
    environment:
      name: "${{ github.event.inputs.environment }}"

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: Set env by input
        run: |
          echo "TAG_NAME=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Set env by input
        id: tagprefix
        run: |
          if [ "${{ env.TAG_NAME }}" = "test" ]
          then
            echo "TAG_PREFIX=dev" >> $GITHUB_OUTPUT
          elif [ "${{ env.TAG_NAME }}" = "prod" ]
          then
            echo "TAG_PREFIX=test" >> $GITHUB_OUTPUT
          else
            echo "TAG_PREFIX=dev" >> $GITHUB_OUTPUT
          fi

      # Get environment variables from 1password
      - name: Setup .env file
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_URL }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          APP_ENV: ${{ env.TAG_NAME }}
        run: |
          curl -sSfo op.zip \
              https://cache.agilebits.com/dist/1P/op2/pkg/v2.0.0/op_linux_amd64_v2.0.0.zip \
              && unzip -od /usr/local/bin/ op.zip \
              && rm op.zip ;\
          SENTRY=$(op read -n op://sentry/${{ env.TAG_NAME }}/namerequest/SENTRY_DSN)
          echo "$SENTRY"
