name: BCREGISTRY UI CD

on:
  push:
    branches:
      - reuseable-workflow
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
        - dev
        - test
        - prod
      tagname:
        description: "Specify the version (git tag) to deploy"
        required: false
        default: ""

jobs:
  bcregistry-cd:
    runs-on: ubuntu-20.04

  uses: pwei1018/bcregistry-sre/.github/workflows/cicd/ui-cd.yml@reuseable-workflow
    with:
      environment: ${{ inputs.environment }}
      tagname: ${{ inputs.tagname }}
    secrets:
      OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_URL }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
